s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Advertising.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/RuleGo-Advertising.list|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Tracking.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/RuleGo-Tracking.list|
s|https://raw.githubusercontent.com/keelewang/Profiles/master/Surge/Ruleset/Guard/Hijacking.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/keelewang-Hijacking.list|
s|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/blackmatrix7-OpenAI.list|
s|https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Claude/Claude.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/blackmatrix7-Claude.list|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/AI.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/RuleGo-AI.list|
s|https://raw.githubusercontent.com/Semporia/Quantumult-X/master/Filter/TikTok.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/Semporia-TikTok.list|
s|https://raw.githubusercontent.com/keelewang/Profiles/master/Surge/Ruleset/StreamingMedia/Region/HK.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/keelewang-Streaming-HK.list|
s|https://raw.githubusercontent.com/keelewang/Profiles/master/Surge/Ruleset/StreamingMedia/Region/TW.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/keelewang-Streaming-TW.list|
s|https://raw.githubusercontent.com/keelewang/Profiles/master/Surge/Ruleset/StreamingMedia/Region/JP.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/keelewang-Streaming-JP.list|
s|https://raw.githubusercontent.com/keelewang/Profiles/master/Surge/Ruleset/StreamingMedia/Region/US.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/keelewang-Streaming-US.list|
s|https://raw.githubusercontent.com/keelewang/Profiles/master/Surge/Ruleset/StreamingMedia/Streaming.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/keelewang-Streaming.list|
s|https://raw.githubusercontent.com/keelewang/Profiles/master/Quantumult/Filter/StreamingMedia/Video/Netflix.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/keelewang-Netflix.list|
s|https://raw.githubusercontent.com/keelewang/Profiles/master/Surge/Ruleset/StreamingMedia/StreamingSE.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/keelewang-StreamingSE.list|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Proxy.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/RuleGo-Proxy.list|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Proxy%2B.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/RuleGo-ProxyPlus.list|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Apple/Apple.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/RuleGo-Apple.list|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Apple/TestFlight.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/RuleGo-TestFlight.list|
s|https://raw.githubusercontent.com/Semporia/Quantumult-X/master/Filter/China.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/Semporia-China.list|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Direct%2B.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/RuleGo-DirectPlus.list|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/WeChat.list|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/dist/qx/Vendor/RuleGo-WeChat.list|
s|https://raw.githubusercontent.com/ddgksf2013/Rewrite/refs/heads/master/AdBlock/TieBaAds.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/TieBaAds.conf|
s|https://ddgksf2013.top/rewrite/UmetripAds.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/UmetripAds.conf|
s|https://ddgksf2013.top/rewrite/LuckinCoffeeAds.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/LuckinCoffeeAds.conf|
s|https://ddgksf2013.top/rewrite/TencentDocAds.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/TencentDocAds.conf|
s|https://raw.githubusercontent.com/Yuheng0101/X/refs/heads/main/Scripts/ChinaMobile/NoAds.js|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/ChinaMobile-NoAds.js|
s|https://raw.githubusercontent.com/ddgksf2013/Rewrite/refs/heads/master/AdBlock/QiShuiMusicAds.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/QiShuiMusicAds.conf|
s|https://raw.githubusercontent.com/ddgksf2013/Rewrite/refs/heads/master/AdBlock/Applet.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/Applet.conf|
s|https://ddgksf2013.top/rewrite/StartUpAds.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/StartUpAds.conf|
s|https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/CaiYunAds.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/CaiYunAds.conf|
s|https://ddgksf2013.top/scripts/zhihu.ads.js|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/zhihu.ads.js|
s|https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/GoofishAds.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/GoofishAds.conf|
s|https://ddgksf2013.top/rewrite/XiaoHongShuAds.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/XiaoHongShuAds.conf|
s|https://ddgksf2013.top/scripts/bdpan.ads.js|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/bdpan.ads.js|
s|https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/Function/UnblockURLinWeChat.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/UnblockURLinWeChat.conf|
s|https://raw.githubusercontent.com/Semporia/TikTok-Unlock/master/Quantumult-X/TikTok-KR.conf|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/TikTok-KR.conf|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Module/Unlock/bilibili.w.sgmodule|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/bilibili-unlock.sgmodule|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Module/Unlock/AbeamTV.sgmodule|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/AbeamTV.sgmodule|
s|https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Module/Block/Advertising.sgmodule|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Rewrite/qx/Block-Advertising.sgmodule|
s|https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/streaming-ui-check.js|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Scripts/streaming-ui-check.js|
s|https://ddgksf2013.top/scripts/server-info-pure.js|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Scripts/server-info-pure.js|
s|https://raw.githubusercontent.com/chavyleung/scripts/master/chavy.box.js|https://raw.githubusercontent.com/cnsiming/HappyRule/rules/Scripts/chavy.box.js|
